homepage:
    pattern:  /
    defaults: { _controller: FoundationBundle:Default:index }

hello:
    resource: HelloBundle/Resources/config/routing.yml

mapeditor:
    resource: MapEditorBundle/Resources/config/routing.yml
